language: java
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
script:
  - mvn -P ${JPAPROVIDER} install
#after_success:
#  - "bash ./.travis-deploy.sh"
matrix:
  fast_finish: true
  include:
    - env: JPAPROVIDER=hibernate
      jdk: oraclejdk7
    - env: JPAPROVIDER=hibernate-4.3
      jdk: oraclejdk7
    - env: JPAPROVIDER=hibernate-5.0
      jdk: oraclejdk8
    - env: JPAPROVIDER=eclipselink
      jdk: oraclejdk7
    - env: JPAPROVIDER=openjpa
      jdk: oraclejdk7
    - env: JPAPROVIDER=datanucleus
      jdk: oraclejdk7
  allow_failures:
    - env: JPAPROVIDER=hibernate-5.0
      jdk: oraclejdk8
    - env: JPAPROVIDER=eclipselink
      jdk: oraclejdk7
    - env: JPAPROVIDER=openjpa
      jdk: oraclejdk7
    - env: JPAPROVIDER=datanucleus
      jdk: oraclejdk7