language: java
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
addons:
  postgresql: "9.3"
before_install:
  - sh -c "if [ '$RDBMS' = 'db2' ]; then sh travis/before_install_db2.sh; fi"
  - sh -c "if [ '$RDBMS' = 'firebird' ]; then sh travis/before_install_firebird.sh; fi"
  - sh -c "if [ '$RDBMS' = 'oracle' ]; then sh travis/before_install_oracle.sh; fi"
install:
  - sh -c "if [ '$JDK' = '9' ]; then sh travis/install_jdk9.sh; fi"
  - sh -c "if [ '$LATEST_MAVEN' = 'true' ]; then sh travis/install_latest_maven.sh; fi"
before_script:
  - sh -c "if [ '$JDK' = '9' ]; then sh travis/before_script_jdk9.sh; fi"
  - sh -c "if [ '$RDBMS' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;'; fi"
  - sh -c "if [ '$RDBMS' = 'postgresql' ]; then psql -c 'create database test;' -U postgres; fi"
  - sh -c "if [ '$RDBMS' = 'db2' ]; then sh travis/before_script_db2.sh; fi"
  - sh -c "if [ '$RDBMS' = 'firebird' ]; then sh travis/before_script_firebird.sh; fi"
  - sh -c "if [ '$RDBMS' = 'oracle' ]; then sh travis/before_script_oracle.sh; fi"
after_failure: 
  - sh travis/print_surefire_reports.sh
script:
  - ./build.sh
after_success:
  - "bash ./.travis-deploy.sh"
# Leave out jdk switch because on the legacy infrastructure this won't work
# No big deal because oraclejdk7 is the default anyways
#jdk:
#  - oraclejdk7
env:
  global:
    - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"
matrix:
  fast_finish: true
  include:
# hibernate
    - env: JPAPROVIDER=hibernate RDBMS=h2
    - env: JPAPROVIDER=hibernate RDBMS=mysql
    - env: JPAPROVIDER=hibernate RDBMS=postgresql
#    - env: JPAPROVIDER=hibernate RDBMS=sqlite
# hibernate-4.3
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=h2
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=mysql
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=postgresql
#    - env: JPAPROVIDER=hibernate-4.3 RDBMS=sqlite
# datanucleus-4
    - env: JPAPROVIDER=datanucleus-4 RDBMS=h2
    - env: JPAPROVIDER=datanucleus-4 RDBMS=mysql
    - env: JPAPROVIDER=datanucleus-4 RDBMS=postgresql
# TODO: work on datanucleus-4/sqlite support
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=sqlite
# eclipselink
# TODO: work on eclipselink4/h2 support
#    - env: JPAPROVIDER=eclipselink RDBMS=h2
#    - env: JPAPROVIDER=eclipselink RDBMS=mysql
#    - env: JPAPROVIDER=eclipselink RDBMS=postgresql
#    - env: JPAPROVIDER=eclipselink RDBMS=sqlite
# openjpa
#    - env: JPAPROVIDER=openjpa RDBMS=h2
#    - env: JPAPROVIDER=openjpa RDBMS=mysql
#    - env: JPAPROVIDER=openjpa RDBMS=postgresql
#    - env: JPAPROVIDER=openjpa RDBMS=sqlite
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=mysql
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=postgresql
      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate-5.0 RDBMS=sqlite
#      jdk: oraclejdk8
# datanucleus-5
    - env: JPAPROVIDER=datanucleus-5 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=datanucleus-5 RDBMS=mysql
      jdk: oraclejdk8
    - env: JPAPROVIDER=datanucleus-5 RDBMS=postgresql
      jdk: oraclejdk8
# TODO: work on datanucleus-5/sqlite support
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=sqlite
#      jdk: oraclejdk8
# DB2
    - env: JPAPROVIDER=hibernate RDBMS=db2 LATEST_MAVEN=true
      sudo: true
    - env: JPAPROVIDER=hibernate-4.3 RDBMS=db2
      sudo: true
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=db2
      jdk: oraclejdk8
      sudo: true
# TODO: work on datanucleus-4/db2 support
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=db2
#      sudo: true
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=db2
#      jdk: oraclejdk8
#      sudo: true
#    - env: JPAPROVIDER=eclipselink RDBMS=db2
#      sudo: true
#    - env: JPAPROVIDER=openjpa RDBMS=db2
#      sudo: true
# Firebird
# TODO: work on hibernate/firebird support
#    - env: JPAPROVIDER=hibernate RDBMS=firebird
#      sudo: true
#    - env: JPAPROVIDER=hibernate-4.3 RDBMS=firebird
#      sudo: true
#    - env: JPAPROVIDER=hibernate-5.0 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true
# TODO: work on datanucleus-4/firebird support
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=firebird
#      sudo: true
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=firebird
#      jdk: oraclejdk8
#      sudo: true
#    - env: JPAPROVIDER=eclipselink RDBMS=firebird
#      sudo: true
#    - env: JPAPROVIDER=openjpa RDBMS=firebird
#      sudo: true
# Oracle
# TODO: work on hibernate/oracle support
#    - env: JPAPROVIDER=hibernate RDBMS=oracle
#      sudo: true
#    - env: JPAPROVIDER=hibernate-4.3 RDBMS=oracle
#      sudo: true
#    - env: JPAPROVIDER=hibernate-5.0 RDBMS=oracle
#      jdk: oraclejdk8
#      sudo: true
# TODO: work on datanucleus-4/oracle support
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=oracle
#      sudo: true
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=oracle
#      jdk: oraclejdk8
#      sudo: true
#    - env: JPAPROVIDER=eclipselink RDBMS=oracle
#      sudo: true
#    - env: JPAPROVIDER=openjpa RDBMS=oracle
#      sudo: true
# JDK 9
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=h2 JDK=9
      sudo: true
  allow_failures:
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=sqlite
#    - env: JPAPROVIDER=datanucleus-5 RDBMS=sqlite
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=db2
#      sudo: true
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=firebird
#      sudo: true
#    - env: JPAPROVIDER=datanucleus-4 RDBMS=oracle
#      sudo: true
#    - env: JPAPROVIDER=eclipselink RDBMS=h2
#    - env: JPAPROVIDER=openjpa RDBMS=h2
#    - env: JPAPROVIDER=hibernate RDBMS=firebird
#      sudo: true
#    - env: JPAPROVIDER=hibernate RDBMS=oracle
#      sudo: true
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=h2 JDK=9
      sudo: true