language: java
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
addons:
  postgresql: "9.3"
before_script:
  - sh -c "if [ '$RDBMS' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;'; fi"
  - sh -c "if [ '$RDBMS' = 'postgresql' ]; then psql -c 'create database test;' -U postgres; fi"
after_failure: 
  - sh print_surefire_reports.sh
script:
  - mvn -P ${JPAPROVIDER},${RDBMS} install
#after_success:
#  - "bash ./.travis-deploy.sh"
jdk:
  - oraclejdk7
env:
# hibernate
  - JPAPROVIDER=hibernate RDBMS=h2
  - JPAPROVIDER=hibernate RDBMS=mysql
  - JPAPROVIDER=hibernate RDBMS=postgresql
#  - JPAPROVIDER=hibernate RDBMS=sqlite
# hibernate-4.3
  - JPAPROVIDER=hibernate-4.3 RDBMS=h2
  - JPAPROVIDER=hibernate-4.3 RDBMS=mysql
  - JPAPROVIDER=hibernate-4.3 RDBMS=postgresql
#  - JPAPROVIDER=hibernate-4.3 RDBMS=sqlite
# datanucleus
  - JPAPROVIDER=datanucleus RDBMS=h2
#  - JPAPROVIDER=datanucleus RDBMS=mysql
#  - JPAPROVIDER=datanucleus RDBMS=postgresql
#  - JPAPROVIDER=datanucleus RDBMS=sqlite
# eclipselink
  - JPAPROVIDER=eclipselink RDBMS=h2
#  - JPAPROVIDER=eclipselink RDBMS=mysql
#  - JPAPROVIDER=eclipselink RDBMS=postgresql
#  - JPAPROVIDER=eclipselink RDBMS=sqlite
# openjpa
#  - JPAPROVIDER=openjpa RDBMS=h2
#  - JPAPROVIDER=openjpa RDBMS=mysql
#  - JPAPROVIDER=openjpa RDBMS=postgresql
#  - JPAPROVIDER=openjpa RDBMS=sqlite
matrix:
  fast_finish: true
  include:
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=h2
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=mysql
      jdk: oraclejdk8
    - env: JPAPROVIDER=hibernate-5.0 RDBMS=postgresql
      jdk: oraclejdk8
#    - env: JPAPROVIDER=hibernate-5.0 RDBMS=sqlite
#      jdk: oraclejdk8
  allow_failures:
    - env: JPAPROVIDER=datanucleus
    - env: JPAPROVIDER=eclipselink
#    - env: JPAPROVIDER=openjpa